language: ruby
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: riTWFG4X+/bEalykwlVWFlZKUWb6SnPR5UzYRDuKPF3YbrE7gtBg9TsuzBpJVjuMdFjw5iqnVl4byHL7hLoCQquDkvPYOCBZdGegO88RMry8YQJHROwDcVVPMDrUzCdLEF5L3OSaexxJDvV/jTfsOWmxGbvDi88f6/D+TcXMoEwrIt8pOWDl7GasBaYU5KCW+F9ilgHv8S3wpQaJrqKZ/6gJFB73r5TaiD71YOvYBVaS0DIzOhRVBm8Jsxpp3OKlIcc3wWqm33+aw//xOjSUxa0jNzZTfLgrFjvg+Oa4TC0D8IUtafDgVVqDMhLeWhO8frRxVErDZnGF7xgfcPy2PBDgN2u+SRHspH2Gn69klKxh+tr2wuNoU3/M6Zq1E6pwvTZYNk3BxW/Elahu82UW+hS8RpS/DMfyXJu6lXEgeLyrmL1CaMU/Mp/Byq+n/g5xN1SGDZYdt/DXsHvZWgbNuAg2Wckqfx+vNzwbnzUJfsqD2G1/dZlEBFBXNkzEqhMc80gTrQml+1F/yQFwMFQR9AD8DuI/f2e/SYbTUXKZmlbnD8Q7iDY0crfG/6wHkHBWNYPslRLxdoIyZOnSuuoglPWEqNsFx/eB6oxwDZeJvM1LidQThgfGPUvBKDbMEhsRV1ISkwLbL6QIDs7fUDsjwkiW2zuLqKcrJyQk5nRK1hE=
  app: booktrix-server
  on:
    repo: wampir1408/Booktrix-server
