language: ruby
rvm:
- 2.4.0
deploy:
  api_key:
    secure: S9rLts63M0GpXH5O1KU+2Dn+9k6aJUyU/hTGh5QFqFnevQ6QdoZXmfQhkwipGCBS6xIgbHwCvqxaQXEm77RDfvYlY2wzfR757FLQd8Bc+RNTvaP75OH/mYKPCccPEnNZGjL5W3/mdadulFDK2nRjH7bmoJAVaiA5nfvjUrf4YfcVyxFZOGSRNydXnHUW5X40S9HYIIEvCIbB+nw4pHho2rWGWW4CMCtfN+4TLbnmwrLK/Xl8rT+MTqpzrOQVLkizIJTwk4xkZUcGt20BkoJEWz9Siq3d8GFpcA29SNQXjEVWHeptEUOnkMHo9izWEouZyU4xcZSvcFnnifyVgfta7+532PMR7sMr0W5YMW6XqKdDdbJvg5KT5e5Zd0Irx2x6jD/tMTzWTV3eVUKfPpnb5hISP2pjucB8P27crxNhpEWG1Pw0tEQm1zUeCcbmjTa9xEu5y6RBsYHrjFbZIthTNrdkR8BGynrGSg58tdfaTk9R5ChjkHFCNo4Ed8rX6no3L4BQr+GZCnOmIEJvyiKy47fXmsj3au282ajU+gy3PxqMet2DurFvOwaRxUNOPnm580bNcUjOxYI0CshESGbf4vBcremxvcvJbLDybvMToEjibiozJVjdmvuTzXoe80W7+fXInEL6W3gXx/JeE3EdHO+SusqGoH8yzZJLbqNWXB0=
