# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd2562b24c78fa910626072c02eeef1f10c7485c346aa2a05e462037d768b0e81e70cb1e4219b3f46a76e898ba6285551f851fb9498468aeddbc3c551f994c7a

test:
  secret_key_base: fef385190c8c65a20abe33745e130cf82a963a773ccb7154c752828770a958e14741efc8c93aeec8fd0702ed57ff859e9016cab4e2db0d2bd55f02cc7fb3c928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
